name: Custom Action
description: This action accepts two parameters and prints them.
author: Your Name

inputs:
  param1:
    description: 'Parameter 1'
    required: true
  param2:
    description: 'Parameter 2'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
